language: generic

# optionally specify a list of environments, for example to test different RDBMS

# env:
#   - DB=mysql
#   - DB=pgsql

# before_script:
#   - if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
#   - bash packager --add $TRAVIS_TAG $TRAVIS_TAG
#   - bash packager pull

script: 
  - bash packager build
  - bash packager publish

# after_script:
  