language: generic

# optionally specify a list of environments, for example to test different RDBMS

env:
  global:
  - ENCRYPTION_LABEL: "62c64065c72c"
  - COMMIT_AUTHOR_EMAIL: "travis@cocomake.co"
  - COMMIT_AUTHOR_NAME: "Travis CI"

# before_script:
#  - if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
#  - bash packager --add $TRAVIS_TAG $TRAVIS_TAG
#  - bash packager pull
cache:
  directories:
    - $HOME/build

script: 
  - bash packager build
  - bash packager publish

# after_script:
