#!/bin/bash

function check_file_exists()
{
	local _FILE_NAME=${1}
	
	if [ -f "${_FILE_NAME}" ]
	then
		return 0 #true
	else
		return 1 #false
	fi	
}


if check_file_exists "./ArduinoPackager/packager"
then
	RELEASE_REPO_BRANCH="master"
	source "./setup_git_credential"
	source "./ArduinoPackager/packager"
else
	echo "first time running packager.. fetching submodule.."
	git pull && git submodule init && git submodule update && git submodule status
	git submodule foreach git reset HEAD --hard
fi

